import React from "react";

import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.scss'
import { javascript } from "@codemirror/lang-javascript";
import { html } from '@codemirror/lang-html';
import { css } from '@codemirror/lang-css';
import Editor from './components/Editor';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Code Editor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.editor}>
        </div>

        <div className={styles.center}>
          
        </div>
        <section className={styles.editorContainer}>
          <Editor title="HTML" extensions={[html({ matchClosingTags: true })]} />
          <Editor title="CSS" extensions={[css()]} />
          <Editor title="Javascript" extensions={[javascript({ jsx: true })]} />
        </section>

        
      </main>
    </>
  )
}
