import React from "react";

import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import { javascript } from "@codemirror/lang-javascript";
import { html } from '@codemirror/lang-html';
import { css } from '@codemirror/lang-css';
import {aura} from '@uiw/codemirror-theme-aura';
import { useState } from "react";

import Editor from './components/Editor';
import CodeRunner from "./components/CodeResult";


export default function Home() {
  const themes = {
    'aura': {theme: aura, bgColor: 'rgb(34,31,47)', color: 'cyan'}
  }
  const [themeName, setThemeName] = useState('aura');
  const [theme, setTheme] = useState(themes[themeName]);
  const [htmlValue, setHTMLValue] = useState('');
  const [cssValue, setCSSValue] = useState('');
  const [jsValue, setJSValue] = useState('');
  const langs = {
    html: {
      title: "HTML",
      extensions: [html({ matchClosingTags: true })],
      fn: setHTMLValue
    },
    css: {
      title: "CSS",
      extensions: [css()],
      fn: setCSSValue
    },
    javascript: {
      title: "Javascript",
      extensions: [javascript({ jsx: true })],
      fn: setJSValue
    }
  }
  
  const matchThemeColor = () => {
    if (theme) console.log(themes['aura']);
  }
  
  const renderEditor = (lang, index) => {
    return <Editor key={index} themeColor={theme.color} themeBgColor={theme.bgColor} setCodeValue={lang.fn} theme={theme || aura} title={lang.title} extensions={lang.extensions} />
  }

  const run = () => {
    if (typeof window === 'object') {
      const doc = document.getElementById('code-runner').contentWindow.document;
      doc.open();
      doc.write(`<script>${jsValue}</script>`)
      doc.write(`<style>${cssValue}</style>`)
      doc.write(htmlValue);
      doc.close();
    }
  }
  return (
    <>
      <Head>
        <title>Code Editor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        
        <section className={styles.editorContainer}>
          {Object.keys(langs).map((item, index) => {
            return renderEditor(langs[item], index)
          })}
        </section>

        <section>
          <CodeRunner themeBgColor={theme.bgColor} htmlValue={htmlValue}/>
        </section>
        <button onClick={() => run()}>run</button>
      </main>
    </>
  )
}
